plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id 'com.diffplug.spotless'
}

legacyForge {
    mcpVersion = minecraft_version
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava(sourceSets.main.java.srcDirs.find { it.exists() })
    commonResources(sourceSets.main.resources.srcDirs.find { it.exists() })
}
